/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={`${styles.header} ${inter.className}`}>
        <nav className={styles.navigation}>
          <Link href="/">Home</Link>
          <Link href="/">Products</Link>
          <Link href="/">Blog</Link>
          <Link href="/">Recipes</Link>
        </nav>
      </header>
      <main className={`${styles.main} ${inter.className}`}>
        <section className={styles.grid}>
          <div className={styles.featured}>
            <img
              alt="placeholder"
              src="https://via.placeholder.com/1024x768/eee?text=4:3"
              width={600}
            ></img>
            <div className={styles.text}>
              <h3>Lorem ipsum dolor sit amet</h3>
              <p>
                Faucibus interdum posuere lorem ipsum dolor sit amet
                consectetur. Ipsum dolor sit amet consectetur adipiscing elit ut
                aliquam purus.
              </p>
            </div>
          </div>
          <div className={styles.first}>
            <img
              alt="placeholder"
              src="https://via.placeholder.com/1024x768/eee?text=4:3"
              width={230}
            ></img>
            <div className={styles.text}>
              <h3>Lorem ipsum dolor sit amet</h3>
              <p>
                Faucibus interdum posuere lorem ipsum dolor sit amet
                consectetur.
              </p>
            </div>
          </div>
          <div className={styles.second}>
            <img
              alt="placeholder"
              src="https://via.placeholder.com/1024x768/eee?text=4:3"
              width={230}
            ></img>
            <div className={styles.text}>
              <h3>Lorem ipsum dolor sit amet</h3>
              <p>
                Ipsum dolor sit amet consectetur adipiscing elit ut aliquam
                purus.
              </p>
            </div>
          </div>
          <div className={styles.third}>
            <img
              alt="placeholder"
              src="https://via.placeholder.com/1024x768/eee?text=4:3"
              width={230}
            ></img>
            <div className={styles.text}>
              <h3>Lorem ipsum dolor sit amet</h3>
              <p>
                Faucibus interdum posuere lorem ipsum dolor sit amet
                consectetur.
              </p>
            </div>
          </div>
        </section>
        <section className={styles.stack}>
          <div className={styles.card}>
            <img
              alt="placeholder"
              src="https://via.placeholder.com/1024x768/eee?text=4:3"
              width={372}
            ></img>
            <div className={styles.text}>
              <h3>Lorem ipsum dolor</h3>
              <p>
                Faucibus interdum posuere lorem ipsum dolor sit amet
                consectetur.
              </p>
            </div>
          </div>
          <div className={styles.card}>
            <img
              alt="placeholder"
              src="https://via.placeholder.com/1024x768/eee?text=4:3"
              width={372}
            ></img>
            <div className={styles.text}>
              <h3>Lorem ipsum dolor</h3>
              <p>
                Faucibus interdum posuere lorem ipsum dolor sit amet
                consectetur.
              </p>
            </div>
          </div>
          <div className={styles.card}>
            <img
              alt="placeholder"
              src="https://via.placeholder.com/1024x768/eee?text=4:3"
              width={372}
            ></img>
            <div className={styles.text}>
              <h3>Lorem ipsum dolor</h3>
              <p>
                Ipsum dolor sit amet consectetur adipiscing elit ut aliquam
                purus.
              </p>
            </div>
          </div>
        </section>
      </main>
      <footer className={`${styles.footer} ${inter.className}`}>
        © 2023 - All rights reserved.
      </footer>
    </>
  );
}
